FROM python:3.11-slim as base

RUN apt-get update && apt-get install -y \
    r-base wget unzip default-jre \
    && rm -rf /var/lib/apt/lists/*

RUN pip install numpy pandas matplotlib

# نصب FastQC
RUN wget -q https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip \
    && unzip fastqc_v0.12.1.zip -d /opt/ \
    && chmod +x /opt/FastQC/fastqc \
    && ln -s /opt/FastQC/fastqc /usr/local/bin/fastqc \
    && rm fastqc_v0.12.1.zip

WORKDIR /workspace
ENTRYPOINT ["fastqc"]
CMD ["--help"]
